ansible_user: ENC[AES256_GCM,data:IomCNg==,iv:XcdD753lU7nxVPkIXqQnBbJDhcFof+S2E62cxoJpckY=,tag:czr2uA47FeDCNLMtA3Enbw==,type:str]
inventory_domain: ENC[AES256_GCM,data:9gGB0xZHJCNGES5gxtsnKkvHvw==,iv:0qBy+s3mZzRH5O6RgY3AssG4e5PS5zVrOMNfceHc9s4=,tag:DmDm4oHX/EcGROdN60CS9Q==,type:str]
inventory_fqdn: ENC[AES256_GCM,data:ziLfJVHAYg4S71cESjLt4EFMBRXPfw/dlcL4qxbyzakFymKm549JTinIRV1fO2K4ALiT,iv:a6TDeyKeal1gHGSU25bjpGPBgFZMkGOv7wFLC9YlJxw=,tag:5BTECTmpCRvGuV9imcwd6A==,type:str]
ansible_host: ENC[AES256_GCM,data:jWAzp+eVeYOgd4THew4T9j/1cGNmJs/qdaS6+5cDedizaR3zPSxHDAQUCaKoYOSuia0+4Lk=,iv:p8Hct0p2xXpWNuSnzMZJBySxVi8pl0OpyOrwS6Xmhzo=,tag:Ppw+3W/+i3Yawqy0wKWnHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-25T11:13:01Z"
    mac: ENC[AES256_GCM,data:ezr7CsrWDqBb/J/0ZvhrX85IKoseCibToSuud3PbWT2dxbye0tzqpRkPvtuF8mqS+Jg34O7uJx8F4PPP4sPeYD8EPYUbxlBn6dMTFM986+Boil8ggmqauhDiQlfWZrj6cwidg8IzazP4DArEdJ6/XR96Nr9Stw2va681JsZRQVM=,iv:pHXktbs3nMgjbIVZuLgUdem6CbFAggSTns9BBnnDS2Q=,tag:1P0t/NuPHa9Ef/2eMAqCxA==,type:str]
    pgp:
        - created_at: "2023-06-23T05:50:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DgVp2h0rFsTMSAQdAzBpDeg55xd4cMopLTC1oTUmhxBkyrAlW8/mgIAWDxi0w
            tcfe5zBgXjJkSQ9Dr9YzTdPN/mnkme7h462ziuVuPnNBL/NW7C4NC59yN3oEX49y
            0lwBt1Zdl4Eiysx4USrZB2gt1B38zMQbPtTwRUeGsj1trjIxPQSfJ0HMoDf/NOnX
            IMbiu4JRig1ZPndKjmnLi+VQUx60VZIuNZwbtBBoENt8/zUIbiolX5K/CbQU2w==
            =XNnw
            -----END PGP MESSAGE-----
          fp: E00A62ADD038B3EA078EC06758E213AF974958D7
    unencrypted_suffix: _unencrypted
    version: 3.7.3
