k3s_service_statedir: ENC[AES256_GCM,data:YHkWfqFQrmX3bhdQvg==,iv:AWf40Zt8AZGCIx9o+rKHrFrgcQjRFyd5KUdVDUeQXLQ=,tag:q2LTud//DP5UhsIyfVzN4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-27T20:46:17Z"
    mac: ENC[AES256_GCM,data:HvmaBSbl8DOtrlM/0arXwDKnBhO0gkXOvjCpor+Jz9jJscDmzWbfDDDZD0ihWgK7YF+L1Cl4tyJByUP4fhVR3MRi7IleYDT2rzwqRoHHZQeSX7Vi8SORFpr+ArVt++4+nrAiGH78gY90wlv4Oj7ozlfiSh3BTZMGfdC0HVTMZZk=,iv:HejVl4JgVYQFZ5sAvEXEUCn65AYStP0dJLoeZzDqqkE=,tag:0U6oHOr/TsYtnSp5HR2MFg==,type:str]
    pgp:
        - created_at: "2023-06-25T12:19:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DgVp2h0rFsTMSAQdASkRUxFIYXKWfIVPyNc4AQAKKLo2N1PcjG7kxF7UwiTYw
            tew79yStOp2rZJNxzSdV+xcuY1evv7ADP2urzJiN1AdN67NM8b0ygy6sqoXXVG/u
            0l4BTPliXQwiNUheeaUNuR7YNsz6K3K6YT8YRs3riTFr0kpUX1StlV79lsldRh3P
            6nzz3XP1LVizYDOXdtTpfPpSw1Ltekpce+VtTiNbItr0sYg2HuIlZVbjtaO950ej
            =lnZv
            -----END PGP MESSAGE-----
          fp: E00A62ADD038B3EA078EC06758E213AF974958D7
    unencrypted_suffix: _unencrypted
    version: 3.7.3
