ansible_user: ENC[AES256_GCM,data:GdaAgi5n,iv:ky07IiGHGlVbFT4/3CFQLNcJQQnmTl9mGu4FN/RyrNE=,tag:kUFj36iR3UvW1u540t/5Zg==,type:str]
ansible_become: ENC[AES256_GCM,data:Woh+pQ==,iv:5pct/4JDO9uUQWHh6F0jQZMwniR4ss4MhvTxF4M1duc=,tag:PiHQwKGGnBxH2j1ZEi7ycA==,type:bool]
tor_bridges:
    - ENC[AES256_GCM,data:5hEQncoZfSekErinB/u451MCEiR6FaNwaIpzPbdZi09f1X/mmghigmulMsfL4fdRhTm0PrxxH26bO9gG,iv:2XJjwUQt1CN0V1dqCU4rgLgi4sRnirjlwX5/+uNJDk4=,tag:mTqs42vboTzhD1OiJReUSA==,type:str]
    - ENC[AES256_GCM,data:0JT5QVmVpcopo1CIQ6mDSCAfck9I+zAwp/V1wkJjTDlN68KKe47KFqJucZt6DXqyerjEtg68iXQu,iv:JecX+Ihjq65fvK8pVs0XAXkqcLnvsFZLu+WJWEzssm8=,tag:39jM6V2M6dDVACG+TU/40A==,type:str]
k3s_node_label:
    - ENC[AES256_GCM,data:jIhz4MMRdjgEBJJt7tutMAEYxRdcT+xXkmyAglLvN9g=,iv:fu/ZpMwZQiGAmwsaxkOyouhupmzKbijWLOI8rkp50SQ=,tag:/52jAGv7h3h3WAAEBvk3OA==,type:str]
    - ENC[AES256_GCM,data:Mg2Cy4Aa9bS+CF48yIwKEQ5ACwbdt8cMJPGQ1MZFGaCC5pB40ZQEvg==,iv:oc2jatZKyOOUebxuEpUJjagNiCXTTfaxiVibAl7Nhx4=,tag:eECrPNWRLqFxNJa6PAMqgw==,type:str]
    - ENC[AES256_GCM,data:fLIIBYa32kersp/3ctk888V40DLWTm0uD2uCtB/NsBqL,iv:9ZScZPLwGcYGngZ4Si/e0eGCjH0s81y9EA9utJPKg2M=,tag:IuNCbLofsBJ13CLs+ZKSxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-27T11:43:27Z"
    mac: ENC[AES256_GCM,data:0JutBZesPR0PnLVZTAUlq8wQVqFmizcRBBPRUsnyiO2A7O1BMsb04VE3igR5tRF69I9P70EDj8wYXRuIE20HCfL13ChakZj0pWEkrTwz9bYoNyIid0thgIUGY+l7Z/EZU0szmvRWYC465cj4LV9nM75uoqcgNAS84RhndGEB4as=,iv:FpRo8zCcYtf/OnAbicoiYpb7dn+uNpPYCjQzYlQ0yMQ=,tag:W1gZNyPNr9jmNDAJptwQNA==,type:str]
    pgp:
        - created_at: "2023-06-17T23:33:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DgVp2h0rFsTMSAQdABIOYNl/Y0ENSd40wocTG3e8anpGjtjNAdHipvCChejQw
            iitoajJS3Dbo2l0g5rFx+IW1TC5US/Qpbe4ZdR7vA1jwzJb2oW2eASqGA450bKVQ
            0lwBu2TiVhhEomq3MBQM/kHehAEgDB0jn9ldlHrMmciTN6LOpe52KCuURsZW8X0F
            cujVmWabS8HBy2rYZPEhRORdbuYilnu8e7wj7fp1DwCXN4Jnl7OczeXzrIoa1g==
            =Otg4
            -----END PGP MESSAGE-----
          fp: E00A62ADD038B3EA078EC06758E213AF974958D7
    unencrypted_suffix: _unencrypted
    version: 3.7.3
