ansible_host: ENC[AES256_GCM,data:iFaJ/FVlMZS92g==,iv:cRoVVZt3EuLS4XfEOJx1klIHwZy5aBVH2g1y92sxoyE=,tag:Ive4zP29Wchl00nGgPNDeA==,type:str]
ansible_user: ENC[AES256_GCM,data:IgJFvH18,iv:Ti3k5lxbScPbxNjIbOeFkLxFrMgMCyidRnYHJylBiac=,tag:fB82WKwrFia362w7mdZyRg==,type:str]
ansible_become: ENC[AES256_GCM,data:4Q7S2g==,iv:cYGnJIbRZxDfI8OtA5cxumDi9qvR+s6EY88hO2Wq5wo=,tag:+bnLYx9IHKreRiQS+FlGTA==,type:bool]
tor_bridges:
    - ENC[AES256_GCM,data:bLbXwvHW67LH1cKEeOWvww3/IcWJtowo86FrJzL71r0m+Gq/TjoU4wCBxB/vxtrxU0gr90xbrWCDmBs2,iv:a1A9OeqY9Jwjj70g3+hEB6igwsNR4LlMQ6AoWQH3czY=,tag:fExJoMDek0oG5xIFVKdjhA==,type:str]
    - ENC[AES256_GCM,data:Z8Ech7kcMFcFmIko4hAnJr2Jh07JKvvSjA7hNg/2cqqC/Fwyyo7Uq4+PTkI9yZUP3PTbOHTyUdf1,iv:zNgOz9DZT9D/U1C2/E4Tm1/XWYRbfC/qXpTyXOX6umM=,tag:KZSD1lB8834JYAri2zZ1pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-23T07:49:13Z"
    mac: ENC[AES256_GCM,data:E/wPBfHBdyz2q93tmUqxWMQWqL8WpljaG76pB1eGqeHikfo4Xmp9iC3xoB/ITCCeVa3A6R/6JPll3sUhjpGZtEr1J9m1POUL7gW+xJuVOZ2QFR/ebED5jlNfwYzFseW4tsK3UWi1UEqe6OOLDsY8BfICtArxNzuz8wR1e9lIfgE=,iv:Lm8mU+LXzaEnDHuy/XaCbnX7Gd23MiaXmxiZtvdu8Gk=,tag:hChFEs/kZcNhZ4BpROU3rg==,type:str]
    pgp:
        - created_at: "2023-06-23T07:49:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DgVp2h0rFsTMSAQdA/4ehbcvBJgO5XC4AOvkFeHMngYfg49tJnB3BTryWxCMw
            49yLYIMPnv8WFrFsX8uLuaRflCE8JPNK7u4xs2ij5CLrAYGVX49zo/NfvScKHqxM
            0l4BQjNZ6BDzof/VNbo3gYEs0Qpt5jytA1OhaPB67pEO6D3MyXaeoioIsQz99lFY
            /1093HapKy4SqTcl1rnY6ywfXf1CmBanN+dVf6uySqG1aQ0zk5l30iPEp9WP3knt
            =qflX
            -----END PGP MESSAGE-----
          fp: E00A62ADD038B3EA078EC06758E213AF974958D7
    unencrypted_suffix: _unencrypted
    version: 3.7.3
