all:
  hosts:
    headscale-1: {}
    kuberenetes-1: {}
    supermicro-1: {}
    supermicro-2: {}
    supermicro-3: {}
  children:
    vps:
      hosts:
        headscale-1: {}
        kubernetes-1: {}
    baremetal:
      hosts:
        supermicro-1: {}
        supermicro-2: {}
        supermicro-3: {}
    headscale:
      hosts:
        headscale-1: {}
    tailscale:
      hosts:
        kubernetes-1: {}
        supermicro-1: {}
        supermicro-2: {}
        supermicro-3: {}
    kubernetes_server:
      hosts:
        supermicro-1: {}
    kubernetes_agent:
      hosts:
        kubernetes-1: {}
        supermicro-1: {}
        supermicro-2: {}
        supermicro-3: {}
    kubernetes:
      children:
        kubernetes_server: {}
        kubernetes_agent: {}
