all:
  hosts:
    headscale-1: {}
    supermicro-1: {}
    supermicro-2: {}
    supermicro-3: {}
  children:
    vps:
      hosts:
        headscale-1: {}
    baremetal:
      hosts:
        supermicro-1: {}
        supermicro-2: {}
        supermicro-3: {}
    headscale:
      hosts:
        headscale-1: {}
    tailscale:
      hosts:
        supermicro-1: {}
        supermicro-2: {}
        supermicro-3: {}
