all:
  hosts:
    headscale-1: {}
    supermicro-1: {}
  children:
    prerequisite:
      hosts:
        headscale-1: {}
    headscale:
      hosts:
        headscale-1: {}
    tailscale:
      hosts:
        supermicro-1: {}
