version: '3'

services:
  tor:
    image: ghcr.io/andreygubarev/tor:0.3.1

  socat:
    image: ghcr.io/andreygubarev/socat:0.1.0
    environment:
      - SOCAT_BIND_TYPE=tcp-listen
      - SOCAT_BIND_IFACE=8514
      - SOCAT_BIND_OPTS=fork,reuseaddr
      - SOCAT_CONNECT_TYPE=socks4a:tor
      - SOCAT_CONNECT_IFACE=${HEADSCALE_AUTH_SERVER}
      - SOCAT_CONNECT_OPTS=socksport=9050
    ports:
      - 8514:8514
    restart: unless-stopped
