---
- name: Setup VPS
  hosts: vps
  roles:
    - role: setup

- name: Setup network server
  hosts: network_server
  roles:
    - role: network_server

- name: Setup network agents
  hosts: network_agent
  roles:
    - role: network_agent
