---
- name: Setup Tor Proxy
  hosts: headscale:tailscale
  tasks:
    - name: Install torproxy
      ansible.builtin.include_role:
        name: andreygubarev.proxy.tor

- name: Setup Headscale
  hosts: headscale
  tasks:
    - name: Install headscale
      ansible.builtin.include_role:
        name: andreygubarev.tailscale.headscale
      vars:
        headscale_advertise_proto: http
        headscale_advertise_addr: "{{ tor_hiddenservice_hostname }}"
        headscale_advertise_port: "{{ tor_hiddenservice_port }}"

    - name: Create tailscale directory
      ansible.builtin.file:
        path: /mnt/local/tailscale
        state: directory
        owner: root
        group: root
        mode: '0755'

- name: Set auth key
  hosts: headscale:tailscale
  tasks:
    - name: Get auth key  # noqa: run-once[task]
      ansible.builtin.shell: |
        set -euo pipefail
        headscale -c {{ headscale_confdir }}/config.yaml users create cluster || true
        headscale -c {{ headscale_confdir }}/config.yaml preauthkeys create -u cluster
      args:
        executable: /bin/bash
      delegate_to: "{{ groups['headscale'][0] }}"
      run_once: true
      register: headscale_auth_key
      changed_when: false

    - name: Set auth key
      ansible.builtin.set_fact:
        tailscale_auth_key: "{{ headscale_auth_key.stdout_lines[-1] }}"
      delegate_to: "{{ groups['headscale'][0] }}"

- name: Setup Tailscale
  hosts: tailscale
  tasks:
    - name: Install tailscale
      ansible.builtin.include_role:
        name: andreygubarev.tailscale.tailscale
