version: '3'

services:
  tor:
    image: ghcr.io/andreygubarev/tor:0.3.1
    restart: unless-stopped

  socat:
    image: ghcr.io/andreygubarev/socat:0.1.0
    environment:
      - SOCAT_BIND_TYPE=tcp-listen
      - SOCAT_BIND_IFACE=8514
      - SOCAT_BIND_OPTS=fork,reuseaddr
      - SOCAT_CONNECT_TYPE=socks4a:tor
      - SOCAT_CONNECT_IFACE=${HEADSCALE_AUTH_SERVER}
      - SOCAT_CONNECT_OPTS=socksport=9050
    restart: unless-stopped
    depends_on:
      - tor

  tailscale:
    image: ghcr.io/andreygubarev/tailscale:0.2.3
    environment:
      - TS_AUTHKEY=${HEADSCALE_AUTH_TOKEN}
      - TS_USERSPACE=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--hostname=client-1 --login-server http://socat:8514
      - TS_SOCKS5_SERVER=:1080
    ports:
      - 1080:1080
    volumes:
      - tailscale:/var/lib/tailscale
    restart: unless-stopped
    depends_on:
      - socat

volumes:
  tailscale:
