version: '3'

services:
  torproxy:
    image: ghcr.io/andreygubarev/torproxy:0.1.3
    volumes:
      - tor:/var/lib/tor
    restart: unless-stopped

  tailscale:
    image: ghcr.io/andreygubarev/tailscale:0.2.3
    environment:
      - TS_AUTHKEY=${HEADSCALE_AUTH_TOKEN}
      - TS_USERSPACE=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--hostname=client-1 --login-server http://localhost:8514
      - TS_SOCKS5_SERVER=:1080
      - SOCAT_BIND_TYPE=tcp-listen
      - SOCAT_BIND_IFACE=8514
      - SOCAT_BIND_OPTS=fork,reuseaddr
      - SOCAT_CONNECT_TYPE=socks4a:torproxy
      - SOCAT_CONNECT_IFACE=${HEADSCALE_AUTH_SERVER}
      - SOCAT_CONNECT_OPTS=socksport=9050
    ports:
      - 1080:1080
    volumes:
      - tailscale:/var/lib/tailscale
    restart: unless-stopped
    depends_on:
      - torproxy

volumes:
  tor:
  tailscale:
