---
- name: Prerequisite
  hosts: prerequisite
  roles:
    - role: andreygubarev.debian.root_filesystem
      tags: [root_filesystem]
    - role: andreygubarev.debian.allocate_freespace
      tags: [allocate_freespace]
    - role: andreygubarev.debian.lvm
      tags: [lvm]
    - role: andreygubarev.debian.mountpoint
      vars:
        mountpoint_path: /var
        mountpoint_volume: /dev/mapper/vg0-var
      tags: [mountpoint]
    - role: andreygubarev.debian.mountpoint
      vars:
        mountpoint_path: /tmp
        mountpoint_volume: /dev/mapper/vg0-tmp
      tags: [mountpoint]
    - role: andreygubarev.debian.mountpoint
      vars:
        mountpoint_path: /home
        mountpoint_volume: /dev/mapper/vg0-home
      tags: [mountpoint]
    - role: andreygubarev.debian.luks
      tags: [luks]
